#!/bin/env python

import sys
import json
import requests


# TODO: add flags --team and --year for better control


def main():

    api_key = get_api_key("config.json")

    endpoint = get_endpoint()
    url = get_url(api_key, endpoint)
    events = requests.get(url).json()

    for event in events:
        print(event["key"])


def get_endpoint():
    # if year is not given
    if len(sys.argv) == 2:
        return f"team/frc{sys.argv[1]}/events"
    # if year is given
    else:
        return f"team/frc{sys.argv[1]}/events/{sys.argv[2]}"


def get_url(api_key, endpoint):
    base_url = "https://www.thebluealliance.com/api/v3"
    url = f"{base_url}/{endpoint}?X-TBA-Auth-Key={api_key}"
    return url


def printj(data):
    print(json.dumps(data, indent=4))


def get_api_key(file):
    with open(file, "r") as f:
        return json.load(f)["api_key"]


if __name__ == "__main__":
    main()
