#!/bin/env python

import sys
import json
import requests


def main():
    team = sys.argv[1]
    year = sys.argv[2]

    api_key = get_api_key("config.json")

    url = get_events_url(api_key, team, year)
    data = requests.get(url).json()

    for event in data:
        print(event["key"])


def get_events_url(api_key, team, year):
    base_url = "https://www.thebluealliance.com/api/v3"
    call = f"team/frc{team}/events/{year}"
    url = f"{base_url}/{call}?X-TBA-Auth-Key={api_key}"
    return url


def printj(data):
    print(json.dumps(data, indent=4))


def get_api_key(file):
    with open(file, "r") as f:
        return json.load(f)["api_key"]


if __name__ == "__main__":
    main()
