#!/bin/env python

import argparse

from lib import tools


def main():

    # configuration
    args = get_arguments()
    api_key = tools.get_api_key("config.json")

    # get matches
    events = get_events(args)
    urls = get_urls(api_key, events)
    matches = get_matches(urls)

    # print matches
    tools.printj(matches)


def get_matches(urls):
    for url in urls:
        yield from tools.get_json_data(url)


def get_urls(api_key, events):
    for event in events:
        yield tools.get_url(api_key, f"event/{event}/matches")


def get_events(args):
    # if accepting cmd args
    if args.events != []:
        return args.events
    # if accepting standard input
    if args.input:
        return list(get_events_stdin())


def get_events_stdin():
    for line in tools.get_stdin():
        yield line.strip("\n")


def get_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "events", nargs="*", type=str, help="accept command line arguments"
    )
    parser.add_argument(
        "--input", "-i", action="store_true", help="accept standard input"
    )

    args = parser.parse_args()
    validate_args(parser, args)

    return args


def validate_args(parser, args):
    # given no arguments
    if args.input is False and args.events == []:
        parser.error("you must specify one argument")
    # given both arguments
    if args.input is True and args.events != []:
        parser.error("you must specify only one argument")


if __name__ == "__main__":
    main()
