#!/bin/env python

import sys
import requests
import json


def main():

    # read from standard input
    # k = sys.stdin.readline()
    # while k is not '':
    #     k = sys.stdin.readline()
    #     print(k)
    # return

    # configuration
    events = sys.argv[1:]
    api_key = get_api_key("config.json")

    # retrieve event data

    for event in events:
        matches_url = get_url(api_key, event, "matches")
        matches = requests.get(matches_url).json()
        for match in matches:
            print(match)


def get_url(api_key, event, endpoint):
    base_url = "https://www.thebluealliance.com/api/v3"
    call = f"event/{event}/{endpoint}"
    url = f"{base_url}/{call}?X-TBA-Auth-Key={api_key}"
    return url


def printj(data):
    print(json.dumps(data, indent=4, sort_keys=True))


def get_api_key(file):
    with open(file, "r") as f:
        return json.load(f)["api_key"]


if __name__ == "__main__":
    main()
