#!/bin/env python

import argparse

from lib import tools


def main():

    # configuration
    args = get_arguments()
    api_key = tools.get_api_key("config.json")

    # get data
    url = tools.get_url(api_key, args.endpoint)
    events = tools.get_json_data(url)

    # print data
    tools.printpj(events)


def get_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("endpoint")
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    main()
